/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jcruz' at '31/05/16 18:31' with Gradle 2.13
 *
 * @author jcruz, @date 31/05/16 18:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
